### ISSUE TITLE
using node_modules in app.js

### ISSUE THREAD

**Issue by AndersCan** [holepunchto/bare-android#1]
Starting this app works as expected, but making any meaningful change to app.js does not work as expected.

How do I make this work?
```
// app.js
const http = require('bare-http1');
``` 

logcat: `2024-02-28 20:47:09.504  8124-8124  libc com.holepunch.bare A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 8124 (.holepunch.bare), pid 8124 (.holepunch.bare)`

I've added the package to package.json#dependencies

**Comment by kasperisager** [comment]
Hi @AndersCan! `bare-http1` is a native addon and so has native code that must be linked as part of the build. I forgot to add that bit to the build definition as the example code doesn't make use of native addons, that has been corrected in https://github.com/holepunchto/bare-android/commit/9f8ae99f7edfd8e702878d0aee4da6e7f2931995. It requires https://github.com/holepunchto/cmake-bare/commit/d72c30fa28afd516beecc436d01b6b856ab5be9a which has been released in `bare-dev` v0.8.6 so make sure to upgrade before doing another build.

**Comment by AndersCan** [comment]
@kasperisager Thanks, will test this out later today.

Must admit I can barely (no pun intended) understand these CMakeList.txt 😅
