### ISSUE TITLE
CMake: `include could not find the requested file` (bare)

### ISSUE THREAD

**Issue by gmaclennan** [holepunchto/bare-android#3]
Attempting to try out this repo at https://github.com/holepunchto/bare-android/commit/9732a865cc2c344cb44a8876a5bdbfd8c5897f5c

When running Gradle Sync in Android Studio I see these errors:

```
CMake Error at CMakeLists.txt:5 (include):
include could not find requested file:
CMake Error at CMakeLists.txt:7 (install_node_modules):
Unknown CMake command "install_node_modules". : com.android.ide.common.process.ProcessException: -- The C compiler identification is Clang 18.0.1
```

`CMakeLists.txt:7` is `include(bare)`.

I don't know how CMake works, but maybe this is due to dropping Bare as a submodule?

**Comment by kasperisager** [comment]
If you're not building the project with `bare-dev` you'll need to manually configure your CMake module path so it knows where to find the Bare CMake modules. The modules ship with `bare-dev` and you can use its `paths` command to find the correct path.

**Comment by kasperisager** [comment]
For reference, the module path is forwarded from an environment variable to CMake here: https://github.com/holepunchto/bare-android/blob/9732a865cc2c344cb44a8876a5bdbfd8c5897f5c/app/build.gradle#L20

**Comment by gmaclennan** [comment]
Is there any documentation anywhere about how to use bare-dev? How would I build this project with bare-dev?

**Comment by kasperisager** [comment]
Not yet, but we should put something together soon. For lack of that, you can always find the exact build steps in the Actions workflows: https://github.com/holepunchto/bare-android/blob/main/.github/workflows/test.yml

**Comment by gmaclennan** [comment]
Thanks, that is now working for me, and I can get the app running. FYI I don't see any `console.log` output from bare, but I do see that it is running because the IPC message is being received by the Java side and being logged there.

**Comment by kasperisager** [comment]
Great! `console.log()`s are currently always written to standard I/O, not the Android log. I'll add a build option in Bare to use the Android log instead.

**Comment by kasperisager** [comment]
https://github.com/holepunchto/bare/pull/34
